name: auto-dy2bili

on:
  schedule:
    - cron: "30 11 * * *"  # 19:30 北京时间
    - cron: "30 12 * * *"  # 20:30
    - cron: "30 13 * * *"  # 21:30
    - cron: "30 14 * * *"  # 22:30
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装所需包
        run: pip install -r requirements.txt

      - name: 还原dy配置文件
        run: |
          sed "s|__DOUYIN_COOKIE__|${{ secrets.DOUYIN_COOKIE }}|g" config/douyin_config.example.yaml > config/douyin_config
          .yaml
          mv config/douyin_config.example.yaml config/douyin_config.yaml

      - name: 还原B站凭证文件
        run: |
          echo '${{ secrets.BILIBILI_CREDENTIALS }}' > config/bili_cookies.json

      - name: 读取上传状态缓存
        uses: actions/cache@v4
        with:
          path: state/uploaded.json
          key: uploaded-state-${{ github.run_id }}
          restore-keys: uploaded-state-

      - name: 运行自动化脚本
        run: python auto_pipeline.py